# Generated by Django 4.0.6 on 2022-07-14 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_tasktype_task_alter_tasktype_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='summary',
            field=models.CharField(max_length=20, verbose_name='summary'),
        ),
    ]
