# Generated by Django 4.0.6 on 2022-07-19 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_task_description_alter_task_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='type',
            name='updated_at',
        ),
    ]
