# Generated by Django 4.0.6 on 2022-07-26 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_remove_type_created_at_remove_type_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(verbose_name='date of creation')),
                ('finished_at', models.DateField(blank=True, verbose_name='date of finishing')),
                ('name', models.CharField(max_length=50, verbose_name='project name')),
                ('description', models.TextField(blank=True, verbose_name='project description')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='webapp.project', verbose_name='tasks'),
            preserve_default=False,
        ),
    ]
