# Generated by Django 4.0.6 on 2022-07-29 10:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_project_task_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 7, 29, 10, 58, 15, 651606, tzinfo=utc), verbose_name='date of creation'),
        ),
    ]
