# Generated by Django 4.0.6 on 2022-07-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_alter_project_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateField(blank=True, verbose_name='date of creation'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='project description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='finished_at',
            field=models.DateField(blank=True, null=True, verbose_name='date of finishing'),
        ),
    ]
