# Generated by Django 4.0.6 on 2022-08-22 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_task_user_remove_project_user_project_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
