# Generated by Django 4.0.6 on 2022-08-23 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_alter_project_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('only_for_lead_and_manager', 'только для капитана или менеджера')]},
        ),
    ]
